### ISSUE TITLE
Compatibility / semantic tests against turf.js

### ISSUE THREAD

**Issue by daniel-j-h** [pyturf/pyturf#16]
Hey @diogomatoschaves :smile: it looks like you are porting / re-implementing turf.js in Python.

It would be great to have a testing harness in place where we compare pyturf's impl. vs turf.js'.

With the same geometry as as input, and the same function (plus arguments), I expect the same outputs for both pyturf and turf.js. Only down to some decimals of course.

It would be great to have this testing to guarantee for compatibility and same semantics.

**Comment by diogomatoschaves** [comment]
Hey @daniel-j-h, thanks for the input :)

There is a testing harness already in place, and it follows quite closely the turf.js one. The same input test cases have been ported, and where possible / needed it was extended further. The output sometimes is different because turf.js tends to test equality to a feature collection made of of the input and output, whereas I opted just to test equality to the output. The current coverage is 96% 🙂

To see the tests executing you should do: `python -m pytest --verbose`

**Comment by diogomatoschaves** [comment]
Or do you mean actually seeing the tests running side by side?

**Comment by daniel-j-h** [comment]
Oh, you already ported all tests over? Cool!

Yeap, I thought more like installing turf.js and pyturf side by side (both in their latest version) and then running their functions on the same test and expecting (roughly) the same output.

**Comment by SteffenHaeussler** [comment]
Yes, the tests are ported. The current tests from turf.js are sometimes extended to achieve a higher code coverage or to cover special cases. From my part, I follow a strict TDD approach and put quite some effort and time into testing.
