### ISSUE TITLE
pyturf vs turfpy

### ISSUE THREAD

**Issue by devleaks** [pyturf/pyturf#51]
While searching for pyturf, I found [turfpy](https://github.com/omanges/turfpy).
What the difference in motivation?
turfpy uses shapely. (and numpy, and scipy.)

**Comment by SteffenHaeussler** [comment]
Probably @diogomatoschaves  has also something to contribute here. He came up with the idea and asked me to support him. 

The idea of porting turf.js came from working with geospatial data on my previous job. I ran constantly in problems, which I could barely resolve or with a lot of effort with geopandas/shapely. So I ended up using turf.js (with help - I don't know much javascript) since it solved my problems faster and more efficiently. So we try to be as near to turf.js as possible. This allows the useage of the test cases from turf.js for this project. Also, this approach prevents the usage of those heavy libraries like shapely, numpy and scipy.  

My motivation:
- I always use open-source in my daily work, so I want to give something back
- fun, I like working on it. It is also good training. Lately, I can't allocate time at the moment, but normally I finish my projects. :)

**Comment by devleaks** [comment]
I think that a real added value when transposing form JavaScript to Python is to try to stick to strict python with a minimum of packages, if any. If you use other packages, that's fine as long as they remain "pure python" scripts. I try to avoid "heavy" libraries that need recompilation, etc. From this perspective, JS does a better job. There is a whole suite of geospatial packages from turfjs to leaflet to graph that is "pure" JS. Python too often relies on existing compiled libraries and "simply" binds to them.
But like you said, as long as we have fun working on those, that's what matters.

**Comment by SteffenHaeussler** [comment]
at the moment we rely only on rtree. Since I work in a different field, I don't have the time to implement the rtree algorithm in python.
